const fs = require('fs');
function edit(p, pairs) { let s = fs.readFileSync(p, 'utf8'); for (const [a, b, all] of pairs) { if (!s.includes(a)) throw new Error('missing in ' + p + ': ' + a.slice(0, 80)); s = all ? s.split(a).join(b) : s.replace(a, b); } fs.writeFileSync(p, s); }
// commands.js: install wrappers at load
fs.appendFileSync('js/commands.js', '\nCMD.install();\n');
// map.js: accept layout parameter
edit('js/map.js', [["  constructor(seed = 1) {\n    this.w = 128; this.h = 128;", "  constructor(seed = 1, layout = 'temple') {\n    this.layout = layout; this.w = 128; this.h = 128;"]]);
// fx.js: burning effect
edit('js/fx.js', [
  ["      case 'missile': this.smoke(e.x, e.y, 1, 0.5); break;\n    }", "      case 'missile': this.smoke(e.x, e.y, 1, 0.5); break;\n      case 'fire': this.fire(e.x, e.y, 3, 26, 0.7); this.smoke(e.x, e.y, 1, 0.6); break;\n    }"],
  ["      case 'blood': break;", "      case 'blood': case 'fire': break;"],
]);
// render.js: perspective override
edit('js/render.js', [
  ["    const hp = G.players[G.human]; const vis = hp.vis;", "    const hp = G.players[G.human]; const vis = UI.viewAll ? G.allVis() : hp.vis;"],
  ["      if (u.owner !== G.human && u.isCloaked && !G.detected(u, G.human)) { if (!visNow(x, y)) continue; u._alpha = 0.16; }", "      if (u.owner !== G.human && u.isCloaked && !G.detected(u, G.human) && !UI.viewAll) { if (!visNow(x, y)) continue; u._alpha = 0.16; }"],
]);
// hud.js: perspective override on minimap + replay label + chat line + loading overlay
edit('js/hud.js', [
  ["    const sc = mr.s / (G.map.w * TILE);\n    ctx.fillStyle = 'rgba(96,40,120,0.6)'; const m = G.map; for (let ty = 0; ty < m.h; ty += 2) for (let tx = 0; tx < m.w; tx += 2) if (m.creep[m.idx(tx, ty)] && p.vis[ty * m.w + tx])",
    "    const sc = mr.s / (G.map.w * TILE); const vis = UI.viewAll ? G.allVis() : p.vis;\n    ctx.fillStyle = 'rgba(96,40,120,0.6)'; const m = G.map; for (let ty = 0; ty < m.h; ty += 2) for (let tx = 0; tx < m.w; tx += 2) if (m.creep[m.idx(tx, ty)] && vis[ty * m.w + tx])"],
  ["    for (const r of m.resources) { if (p.vis[r.y * m.w + r.x] === 0) continue;", "    for (const r of m.resources) { if (vis[r.y * m.w + r.x] === 0) continue;"],
  ["    if (this.pending) HUD.text(ctx, 'Select target: '", "    if (this.mode === 'replay') HUD.text(ctx, 'REPLAY  ' + this.speedName() + '  (+/- speed, Ctrl+V perspective, F10 menu)', Render.W / 2, 23, '#ffe45a', 13, true, 'center');\n    if (this.pending) HUD.text(ctx, 'Select target: '"],
  ["    this.drawCursor(ctx);\n  },\n  drawCursor(ctx) {", "    if (this.chat !== null && this.chat !== undefined) { HUD.bevel(ctx, 10, Render.H - this.consoleH - 40, 420, 24, false, 'rgba(8,10,14,0.9)'); HUD.text(ctx, '> ' + this.chat + (G.frame % 24 < 12 ? '_' : ''), 16, Render.H - this.consoleH - 23, '#e6eaf0', 13); }\n    if (this.loading) { const k = (G.frame - this.loading.start) / Math.max(1, this.loading.target - this.loading.start); HUD.bevel(ctx, Render.W / 2 - 160, Render.H / 2 - 30, 320, 60, true, 'rgba(10,12,16,0.95)'); HUD.text(ctx, 'Loading... re-simulating ' + Math.round(k * 100) + '%', Render.W / 2, Render.H / 2 - 6, '#ffe45a', 14, true, 'center'); ctx.fillStyle = '#3fe83f'; ctx.fillRect(Render.W / 2 - 140, Render.H / 2 + 6, 280 * k, 8); }\n    this.drawCursor(ctx);\n  },\n  drawCursor(ctx) {"],
]);
// ui.js: modes, replay/save, speeds, chat/cheats, menu wiring
edit('js/ui.js', [
  ["  SPEEDS: [0.6, 1, 1.5, 2],", "  SPEEDS: [0.25, 0.375, 0.5, 0.625, 0.75, 0.875, 1, 2, 4, 8], SPEED_NAMES: ['Slowest', 'Slower', 'Slow', 'Normal', 'Fast', 'Faster', 'Fastest', '2x', '4x', '8x'], mode: 'play', viewAll: false, chat: null, loading: null,\n  speedName() { return this.SPEED_NAMES[this.speedIdx]; }, maxSpeedIdx() { return this.mode === 'replay' ? 9 : 6; },"],
  ["speedIdx: 1, accum: 0,", "speedIdx: 6, accum: 0,"],
  ["  start(opts) {\n    G.init(opts); Render.reset();", "  start(opts) {\n    opts = Object.assign({}, opts, { players: opts.players.map(p => Object.assign({}, p, { race: p.race === 'R' ? ['T', 'Z', 'P'][Math.floor(Math.random() * 3)] : p.race })) });\n    this.lastOpts = opts; this.mode = opts.mode || 'play'; this.viewAll = false; this.chat = null; this.loading = null; if (this.speedIdx > this.maxSpeedIdx()) this.speedIdx = this.maxSpeedIdx();\n    G.init(opts); G.recording = this.mode === 'play'; G.log = []; G.pendingCmds = null; G.mission = null; if (opts.mission && typeof Missions !== 'undefined') Missions.begin(opts.mission);\n    Render.reset();"],
  ["  simStep() {\n    if (!this.running) return; const now = performance.now(); const dt = Math.min(1, (now - this.lastT) / 1000); this.lastT = now;\n    if (G.paused || this.menu) return;",
    "  startFromLog(data, mode) {\n    const opts = { players: data.players, seed: data.seed, layout: data.layout, mission: data.mission || null, mode: mode === 'watch' ? 'replay' : 'play' };\n    this.start(opts); G.pendingCmds = { list: data.cmds || [], i: 0 }; G.recording = mode === 'load';\n    if (mode === 'load') this.fastForward(data.frame, () => { G.pendingCmds = null; if (data.cam) { Render.camX = data.cam.x; Render.camY = data.cam.y; this.clampCam(); } });\n  },\n  fastForward(target, done) {\n    this.loading = { target, start: G.frame };\n    const step = () => { const t0 = performance.now(); while (G.frame < target && !G.over && performance.now() - t0 < 40) G.tick(); if (G.frame < target && !G.over) setTimeout(step, 0); else { this.loading = null; done(); } };\n    setTimeout(step, 0);\n  },\n  simStep() {\n    if (!this.running) return; const now = performance.now(); const dt = Math.min(1, (now - this.lastT) / 1000); this.lastT = now;\n    if (G.paused || this.menu || this.loading) return;\n    if (this.mode === 'play' && G.frame > 0 && G.frame % (TPS * 120) === 0 && !(typeof Net !== 'undefined' && Net.active) && !this._autosaved) { this._autosaved = true; Replay.save(false); } else if (G.frame % (TPS * 120) !== 0) this._autosaved = false;"],
  ["    if (k === 'F10') { this.menu = 'pause'; return; }", "    if (k === 'F10') { this.menu = 'pause'; return; }\n    if (this.chat !== null) { e.preventDefault(); if (k === 'Enter') { const line = this.chat.trim(); this.chat = null; if (line) { if (!G.cheat(line)) G.players[G.human].msg(line, 'info'); } } else if (k === 'Escape') this.chat = null; else if (k === 'Backspace') this.chat = this.chat.slice(0, -1); else if (k.length === 1 && this.chat.length < 60) this.chat += k; return; }\n    if (k === 'Enter' && this.mode === 'play' && !(typeof Net !== 'undefined' && Net.active)) { this.chat = ''; e.preventDefault(); return; }\n    if (k === 'F5') { e.preventDefault(); Replay.save(true); return; }\n    if (k === 'F8') { e.preventDefault(); if (Replay.hasAutosave()) Replay.loadAutosave(); return; }\n    if ((k === 'v' || k === 'V') && e.ctrlKey && this.mode === 'replay') { this.viewAll = !this.viewAll; e.preventDefault(); return; }"],
  ["    if (k === '+' || k === '=') { this.speedIdx = Math.min(3, this.speedIdx + 1); return; } if (k === '-') { this.speedIdx = Math.max(0, this.speedIdx - 1); return; }",
    "    if (k === '+' || k === '=') { this.speedIdx = Math.min(this.maxSpeedIdx(), this.speedIdx + 1); return; } if (k === '-') { this.speedIdx = Math.max(0, this.speedIdx - 1); return; }"],
  ["    return { title: 'PAUSED', lines: [], items: [['Resume (Esc)', () => { this.menu = null; }], ['Restart', () => { this.start(this.lastOpts); }], ['Quit to menu', () => this.toMenu()]] };",
    "    if (this.mode === 'replay') return { title: 'REPLAY PAUSED', lines: ['Speed: ' + this.speedName()], items: [['Resume (Esc)', () => { this.menu = null; }], ['Toggle full map view', () => { this.viewAll = !this.viewAll; this.menu = null; }], ['Quit to menu', () => this.toMenu()]] };\n    return { title: 'PAUSED', lines: [], items: [['Resume (Esc)', () => { this.menu = null; }], ['Save game (F5)', () => { Replay.save(true); this.menu = null; }], ['Save replay', () => { Replay.saveReplay(); this.menu = null; }], ['Restart', () => { this.start(this.lastOpts); }], ['Quit to menu', () => this.toMenu()]] };"],
  ["items: [['Continue playing', () => { this.menu = null; G.over = false; }], ['Return to main menu', () => this.toMenu()]] }; }",
    "items: [['Continue playing', () => { this.menu = null; G.over = false; }], ['Save replay', () => { Replay.saveReplay(); }], ['Return to main menu', () => this.toMenu()]] }; }"],
  ["  toMenu() { this.running = false; this.menu = null; document.getElementById('menu').style.display = 'flex'; document.getElementById('game').style.display = 'none'; },",
    "  toMenu() { this.running = false; this.menu = null; this.loading = null; document.getElementById('menu').style.display = 'flex'; document.getElementById('game').style.display = 'none'; const ab = document.getElementById('autosaveBtn'); if (ab) ab.style.display = Replay.hasAutosave() ? 'block' : 'none'; },"],
  ["  $('nopp').addEventListener('change', rebuildOpps); rebuildOpps();", "  $('nopp').addEventListener('change', rebuildOpps); rebuildOpps();\n  const ab = $('autosaveBtn'); if (ab) { ab.style.display = Replay.hasAutosave() ? 'block' : 'none'; ab.addEventListener('click', () => Replay.loadAutosave()); }\n  $('loadBtn').addEventListener('click', () => $('loadFile').click()); $('loadFile').addEventListener('change', e => { if (e.target.files[0]) Replay.fromFile(e.target.files[0], 'load'); e.target.value = ''; });\n  $('replayBtn').addEventListener('click', () => $('replayFile').click()); $('replayFile').addEventListener('change', e => { if (e.target.files[0]) Replay.fromFile(e.target.files[0], 'watch'); e.target.value = ''; });"],
  ["    const opts = { players, seed: parseInt($('seed').value) || 1 }; UI.lastOpts = opts; UI.start(opts);", "    const opts = { players, seed: parseInt($('seed').value) || 1, layout: $('layout') ? $('layout').value : 'temple' }; UI.start(opts);"],
  ["'F1: help  ·  F10: menu  ·  speed ' + this.SPEEDS[this.speedIdx] + 'x (+/-)  ·  ' + this.fps + ' fps'", "'F1: help  ·  F10: menu  ·  F5 save  ·  Enter chat  ·  speed ' + this.speedName() + ' (+/-)  ·  ' + this.fps + ' fps'"],
]);
edit('js/hud.js', [["HUD.text(ctx, 'F1 help  ·  F10 menu  ·  speed ' + this.SPEEDS[this.speedIdx] + 'x (+/-)  ·  ' + this.fps + ' fps', ix + 12, y0 + 50, '#8a93a0', 11, false);", "HUD.text(ctx, 'F1 help  ·  F10 menu  ·  F5 save  ·  Enter chat  ·  speed ' + this.speedName() + ' (+/-)  ·  ' + this.fps + ' fps', ix + 12, y0 + 50, '#8a93a0', 11, false);"]]);
// index.html: menu buttons
edit('index.html', [
  ['    <button id="start">START GAME</button>', '    <button id="start">START GAME</button>\n    <div class="row2"><button id="loadBtn" class="small">LOAD SAVED GAME</button><button id="replayBtn" class="small">WATCH REPLAY</button></div>\n    <button id="autosaveBtn" class="small" style="display:none">CONTINUE AUTOSAVE</button>\n    <input type="file" id="loadFile" accept=".json" hidden><input type="file" id="replayFile" accept=".json" hidden>'],
  ['  .help { margin-top: 16px;', '  .row2 { display: flex; gap: 8px; } .row2 button, button.small { font-size: 13px; padding: 8px; margin-top: 8px; letter-spacing: 1px; }\n  .help { margin-top: 16px;'],
]);
console.log('patched');
